ALTER TABLE packages ADD COLUMN IF NOT EXISTS download_count BIGINT NOT NULL DEFAULT 0;
ALTER TABLE packages ADD COLUMN IF NOT EXISTS popularity_score DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE packages ADD COLUMN IF NOT EXISTS download_count_updated_at TIMESTAMPTZ;
